services:
  web: 
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - VITE_API_URL=http://172.93.163.153:50061/v1
    ports:
      - "80:80"
    networks:
      - docker_stack
    environment:
      - NODE_ENV=production

networks:
  docker_stack:
    external: true